SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE MY_TABELLA
(
  ID          	  	DECIMAL(5) 			        NOT NULL,
  NOME		        VARCHAR2(20 CHAR)         	NOT NULL,
  CONSTRAINT MY_TABELLA_IXU01 PRIMARY KEY (ID)
);
