CREATE TABLE SAMPLE (
    id INT IDENTITY PRIMARY KEY,
    data VARCHAR(100),
    type INT
);

CREATE TABLE FILE_READED (
    NAME VARCHAR(100),
    VAL VARCHAR(100),
    SURNAME VARCHAR(100)
);

CREATE TABLE TABLE_TO_READ (
    ID INT  IDENTITY PRIMARY KEY,
    NOME VARCHAR(100),
    COGNOME VARCHAR(100)
);

INSERT INTO TABLE_TO_READ VALUES (1,'NOME1','COGNOME1');
INSERT INTO TABLE_TO_READ VALUES (2,'NOME2','COGNOME2');
INSERT INTO TABLE_TO_READ VALUES (3,'NOME3','COGNOME3');
INSERT INTO TABLE_TO_READ VALUES (4,'NOME4','COGNOME4');

DELETE FROM SAMPLE;