CREATE TABLE IF NOT EXISTS APP1_SORT_INRAM  (
	JOB_SORT_KEY VARCHAR(1000) NOT NULL PRIMARY KEY ,
	JOB_CONTENT LONGVARBINARY
) ;

CREATE INDEX IF NOT EXISTS APP1_SORT_INRAM_IDX ON APP1_SORT_INRAM(JOB_SORT_KEY);

DELETE FROM APP1_SORT_INRAM;